name: Docker

on:
  push:
    branches: [main, hot-fix, compatibility-breaking-changes]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: [main, hot-fix, compatibility-breaking-changes]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ${{ github.ref_type != 'tag' && 'ghcr.io/' || '' }}
  # github.repository as <account>/<repo>
  IMAGE_NAME: godwoken-web3-indexer-prebuilds

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      # The GHP_CRT secret is password or personal access token with `write:packages` access scope
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.ref_type != 'tag' && github.actor || secrets.DOCKERHUB_USERNAME }}
          password: ${{ github.ref_type != 'tag' && secrets.GHP_CRT || secrets.DOCKERHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}${{ github.repository_owner == 'nervosnetwork' && 'nervos' || github.repository_owner }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: New Commit Build => Build and push Docker image to ${{ env.REGISTRY }}${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
        if: ${{ github.ref_type != 'tag' }}
        uses: docker/build-push-action@v2
        with:
          file: docker/indexer/Dockerfile
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Build and push Docker image with Buildx (don't push on PR)
      # only for new tag
      - name: Official Release Build => Build and push Docker image to https://hub.docker.com/r/nervos/godwoken-web3-indexer-prebuilds
        if: ${{ github.repository_owner == 'nervosnetwork' && startsWith(github.ref, 'refs/tags') }}
        uses: docker/build-push-action@v2
        with:
          file: docker/indexer/Dockerfile
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 30
